title: Stamatis Dimopoulos
description: My personal webpage
theme: just-the-docs
baseurl: ""
url: "https://st-dimopoulos.github.io/"
repository: st-dimopoulos/st-dimopoulos.github.io

permalink: pretty

encoding: utf-8

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-0G8ZJFPNKJ
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

plugins:
  - jekyll-default-layout